services:
#mssql docker
  rentabikewtr-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Renta101!
      - MSSQL_PID=Developer
    ports:
      - 1439:1433
    expose:
      - 1433
    networks:
      - rentabikewtrnet
        
  rentabikewtr-rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin 
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 15673:15672  # RabbitMQ Management UI
      - 5672:5672    # RabbitMQ server
    expose:
      - 15672
      - 5672
    networks:
      - rentabikewtrnet

  # subscriber-service:
  #   restart: unless-stopped  
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   environment:
  #     - RABBITMQ_HOST=rentabikewtr-rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USERNAME=admin
  #     - RABBITMQ_PASSWORD=guest
  #     - SMTP_SERVER=smtp.gmail.com
  #     - SMTP_PORT=587
  #     - SMTP_USERNAME=appadi172@gmail.com
  #     - SMTP_PASSWORD=tijx gzdz dzek rtie  # Make sure to secure this in production!
  #     - ConnectionStrings:konekcija=Server=rentabikewtr-sql,1433;TrustServerCertificate=true;Database=IB210282;User=sa;Password=Renta101!;Encrypt=true;ConnectRetryCount=0
  #   depends_on:
  #     - rentabikewtr-sql
  #     - rentabikewtr-rabbitmq
  #   networks:
  #     - rentabikewtrnet
  
  worker-service:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rentabikewtr-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=appadi172@gmail.com
      - SMTP_PASSWORD=tijxgzdzdzekrtie
      - ENABLE_SSL=true
      - ConnectionStrings=konekcija=Server=rentabikewtr-sql,1433;TrustServerCertificate=true;Database=IB210282;User=sa;Password=Renta101!;Encrypt=true;ConnectRetryCount=0
    depends_on:
      - rentabikewtr-sql
      - rentabikewtr-rabbitmq
    networks:
      - rentabikewtrnet

  rentabikewtr-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:konekcija=Server=rentabikewtr-sql,1433;TrustServerCertificate=true;Database=IB210282;User=sa;Password=Renta101!;Encrypt=true;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Production
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=appadi172@gmail.com
      - SMTP_PASSWORD=tijxgzdzdzekrtie
      - SENDER_NAME=help-desk
      - SENDER_EMAIL=appadi172@gmail.com
      - ENABLE_SSL=true
    ports:
      - 44335:44335
    networks:
      - rentabikewtrnet
    links:
      - rentabikewtr-sql
    depends_on:
      - rentabikewtr-sql
      - rentabikewtr-rabbitmq
          
networks:
  rentabikewtrnet:
    driver: bridge      